# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16dfba5fade18a4e0740cd81111796101cfbed9bf18615143b2160d487830ade353b0154d466a93a52b71bd212231740512ed1826951779fc1e8b523b447a872

test:
  secret_key_base: da6cb889fc0ef201be86b5ed4dd2ee49753b5ccf1db3a190b8e19d1fd13188fa8e67427ee4c4854a34a172f48a63ea275646bda1be64c2c6551a35d25fa4b1c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
